### ISSUE TITLE
Span same image across different monitors

### ISSUE THREAD

**Issue by villamide** [LGFae/swww#121]
Hi there!

Is there any way to span a ultrawide wallpaper across in two monitor setup.
I cannot find the way to do it, I have just been able to put the same image twice (one in each monitor) or use different images for it.
I also have been able to trick this effect by cropping the images with GIMP and then setting each image for the respective monitor.

I was wondering if there's any way to achieve this natively. Since I was trying to implement an script to change background and i don't want to complicate it to much dividing all images I get.

This is my screen configuration in Hyprland.

monitor=DP-2, 2560x1440@60, 0x0, 1
monitor=DP-1, 2560x1440@144, 2560x0, 1

Regards and thanks in advance

**Comment by Horus645** [comment]
Sorry man, I think you will have to go ahead and complicate it. `swww` can display images read from `stdin`, so you can probably use a complicated `imagemagick` of `ffmpeg` command to divide your image in two and just pipe it into `swww`:

```bash
complicated-command-that-divides-the-image-first-half img | swww - --outputs DP-2
complicated-command-that-divides-the-image-second-half img | swww - --outputs DP-1
```

**Comment by villamide** [comment]
Okay. Thank you.
I've achieved it with a really simple script. But I was thinking maybe it could be a "native" way to do it.

Here is the script in case is somewhat useful for anyone


`#!/bin/bash
wallpapers=$HOME/pictures/wide
random=$(ls $wallpapers | shuf | head -1)
random=$wallpapers/$random

# split image
convert -crop 50%x100% $random /tmp/output.png

swww img -o "DP-2" --transition-type random /tmp/output-0.png
swww img -o "DP-1" --transition-type random /tmp/output-1.png
`

**Comment by mahdhatre** [comment]
@villamide, thanks for your script. I am learning to bash, and with help (a lot of help) from chatGPT, I built upon it for my usecase.
For those interested, here's my version. It takes a directory as an argument, converts all the images in it, and let's you choose one of the images to span two monitors. Change `DP-3` and `HDMI-A-2` to your monitors.

# wallspan.sh
```bash
#!/bin/bash
# wallspan.sh
# Parse through a directory, given as argument, converting to spannable images across two monitors, or select spannable images as wallpaper

# Check if a folder argument is provided
if [[ -z $1 ]]; then
    echo "Usage: $0 <folder>"
    exit 1
fi

# Set the target directory
TARGET_DIR="$1"

# Ensure the target directory exists
if [[ ! -d "$TARGET_DIR" ]]; then
    echo "Error: Directory '$TARGET_DIR' does not exist."
    exit 1
fi

# Function to display a header
display_header() {
    echo -e "\n\033[1;34m=========================================\033[0m"
    echo -e "\033[1;34m         Image Processing Script         \033[0m"
    echo -e "\033[1;34m=========================================\033[0m"
}

# Function to display a footer
display_footer() {
    echo -e "\n\033[1;34m=========================================\033[0m"
    echo -e "\033[1;34m           Processing Complete           \033[0m"
    echo -e "\033[1;34m=========================================\033[0m"
}

# Function to parse images
parse_images() {
    echo "Parsing images in $TARGET_DIR..."

    # Find all base names of files with both -0 and -1 suffixes
    declare -A paired_images
    for file in "$TARGET_DIR"/*-0.*; do
        # Check if a corresponding -1 file exists
        base_name="${file%-0.*}"
        if [[ -f "$base_name-1.${file##*.}" ]]; then
            # Mark this base name as having both -0 and -1 files
            paired_images["$base_name"]=1
        fi
    done

    # Process images that do not have corresponding -0 and -1 pairs
    for file in "$TARGET_DIR"/*; do
        # Skip files with -0 or -1 suffix, non-image files, and paired images
        if [[ ! $file =~ -[01]\.[a-zA-Z]+$ ]] && [[ $file =~ \.(png|jpg|jpeg|bmp|gif)$ ]]; then
            base_name="${file%.*}"
            if [[ -z "${paired_images["$base_name"]}" ]]; then
                echo "Parsing $file..."
                magick convert -crop 50%x100% "$file" "$file"
            else
                echo "Skipping $file (already processed)"
            fi
#        else
#            echo "Skipping $file (not a valid image or already processed)"
        fi
    done
    display_footer
}

# Function to display and select background
select_background() {
    echo "Selecting background image in $TARGET_DIR..."

    # Create an associative array for storing image pairs by base name
    declare -A image_pairs
    for file in "$TARGET_DIR"/*-0.* "$TARGET_DIR"/*-1.*; do
        if [[ $file =~ "$TARGET_DIR"/(.*)-[01]\.(png|jpg|jpeg|bmp|gif)$ ]]; then
            base_name="${BASH_REMATCH[1]}"
            image_pairs["$base_name"]=1
        fi
    done

    # List the unique base names
    i=1
    for base_name in "${!image_pairs[@]}"; do
        echo "$i. $base_name"
        image_list[i]="$base_name"
        ((i++))
    done

    # Get user selection
    read -p "Enter the number of the image to set as background: " choice
    selected_base="${image_list[choice]}"

    if [[ -n "$selected_base" ]]; then
        # Find the actual file extensions for -0 and -1 images
        img0=$(find "$TARGET_DIR" -type f -name "$selected_base-0.*" | head -n 1)
        img1=$(find "$TARGET_DIR" -type f -name "$selected_base-1.*" | head -n 1)

        # Ensure both files exist before setting the background
        if [[ -f "$img0" && -f "$img1" ]]; then
            swww img -o DP-3 "$img0"
            swww img -o HDMI-A-2 "$img1"
            echo "Background set for $selected_base."
        else
            echo "Error: Matching image files for $selected_base not found."
        fi
    else
        echo "Invalid selection."
    fi
}

# Main menu
clear
while true; do
    display_header
    echo "Menu:"
    echo "1. Parse images"
    echo "2. Select background"
    echo "3. Exit"
    read -p "Choose an option: " option

    case $option in
        1)
            parse_images
            ;;
        2)
            select_background
            ;;
        3)
            echo "Exiting."
            exit 0
            ;;
        *)
            echo "Invalid option."
            ;;
    esac
done
```

**Comment by ImFenyx** [comment]
> [@villamide](https://github.com/villamide), thanks for your script. I am learning to bash, and with help (a lot of help) from chatGPT, I built upon it for my usecase. For those interested, here's my version. It takes a directory as an argument, converts all the images in it, and let's you choose one of the images to span two monitors. Change `DP-3` and `HDMI-A-2` to your monitors.
> # wallspan.sh
> 
> #!/bin/bash
> # wallspan.sh
> # Parse through a directory, given as argument, converting to spannable images across two monitors, or select spannable images as wallpaper
> 
> # Check if a folder argument is provided
> if [[ -z $1 ]]; then
>     echo "Usage: $0 <folder>"
>     exit 1
> fi
> 
> # Set the target directory
> TARGET_DIR="$1"
> 
> # Ensure the target directory exists
> if [[ ! -d "$TARGET_DIR" ]]; then
>     echo "Error: Directory '$TARGET_DIR' does not exist."
>     exit 1
> fi
> 
> # Function to display a header
> display_header() {
>     echo -e "\n\033[1;34m=========================================\033[0m"
>     echo -e "\033[1;34m         Image Processing Script         \033[0m"
>     echo -e "\033[1;34m=========================================\033[0m"
> }
> 
> # Function to display a footer
> display_footer() {
>     echo -e "\n\033[1;34m=========================================\033[0m"
>     echo -e "\033[1;34m           Processing Complete           \033[0m"
>     echo -e "\033[1;34m=========================================\033[0m"
> }
> 
> # Function to parse images
> parse_images() {
>     echo "Parsing images in $TARGET_DIR..."
> 
>     # Find all base names of files with both -0 and -1 suffixes
>     declare -A paired_images
>     for file in "$TARGET_DIR"/*-0.*; do
>         # Check if a corresponding -1 file exists
>         base_name="${file%-0.*}"
>         if [[ -f "$base_name-1.${file##*.}" ]]; then
>             # Mark this base name as having both -0 and -1 files
>             paired_images["$base_name"]=1
>         fi
>     done
> 
>     # Process images that do not have corresponding -0 and -1 pairs
>     for file in "$TARGET_DIR"/*; do
>         # Skip files with -0 or -1 suffix, non-image files, and paired images
>         if [[ ! $file =~ -[01]\.[a-zA-Z]+$ ]] && [[ $file =~ \.(png|jpg|jpeg|bmp|gif)$ ]]; then
>             base_name="${file%.*}"
>             if [[ -z "${paired_images["$base_name"]}" ]]; then
>                 echo "Parsing $file..."
>                 magick convert -crop 50%x100% "$file" "$file"
>             else
>                 echo "Skipping $file (already processed)"
>             fi
> #        else
> #            echo "Skipping $file (not a valid image or already processed)"
>         fi
>     done
>     display_footer
> }
> 
> # Function to display and select background
> select_background() {
>     echo "Selecting background image in $TARGET_DIR..."
> 
>     # Create an associative array for storing image pairs by base name
>     declare -A image_pairs
>     for file in "$TARGET_DIR"/*-0.* "$TARGET_DIR"/*-1.*; do
>         if [[ $file =~ "$TARGET_DIR"/(.*)-[01]\.(png|jpg|jpeg|bmp|gif)$ ]]; then
>             base_name="${BASH_REMATCH[1]}"
>             image_pairs["$base_name"]=1
>         fi
>     done
> 
>     # List the unique base names
>     i=1
>     for base_name in "${!image_pairs[@]}"; do
>         echo "$i. $base_name"
>         image_list[i]="$base_name"
>         ((i++))
>     done
> 
>     # Get user selection
>     read -p "Enter the number of the image to set as background: " choice
>     selected_base="${image_list[choice]}"
> 
>     if [[ -n "$selected_base" ]]; then
>         # Find the actual file extensions for -0 and -1 images
>         img0=$(find "$TARGET_DIR" -type f -name "$selected_base-0.*" | head -n 1)
>         img1=$(find "$TARGET_DIR" -type f -name "$selected_base-1.*" | head -n 1)
> 
>         # Ensure both files exist before setting the background
>         if [[ -f "$img0" && -f "$img1" ]]; then
>             swww img -o DP-3 "$img0"
>             swww img -o HDMI-A-2 "$img1"
>             echo "Background set for $selected_base."
>         else
>             echo "Error: Matching image files for $selected_base not found."
>         fi
>     else
>         echo "Invalid selection."
>     fi
> }
> 
> # Main menu
> clear
> while true; do
>     display_header
>     echo "Menu:"
>     echo "1. Parse images"
>     echo "2. Select background"
>     echo "3. Exit"
>     read -p "Choose an option: " option
> 
>     case $option in
>         1)
>             parse_images
>             ;;
>         2)
>             select_background
>             ;;
>         3)
>             echo "Exiting."
>             exit 0
>             ;;
>         *)
>             echo "Invalid option."
>             ;;
>     esac
> done

what if I use gif instead of png?
