### ISSUE TITLE
--no-resize does not center images larger than the screen size

### ISSUE THREAD

**Issue by Cephian** [LGFae/swww#156]
The documentation for `--no-resize` claims

> If this is set, the image won't be resized, and will be centralized in the middle of the screen instead.

This is true for images smaller than the screen size, but for larger images the top left of the image is aligned to the top left corner of the screen. I think it makes the most sense to change behavior to be in line with the documentation here and perform a centered crop.

**Comment by Horus645** [comment]
Ah, good point. I hadn't thought of that.
