### ISSUE TITLE
Swww init cannot find swww-daemon

### ISSUE THREAD

**Issue by Blazing-Blast** [LGFae/swww#158]
I have followed the install instructions and added both the binaries into the same folder that is part of `$PATH`. Then after running `swww init` from `~` it gives an error `Error: "error spawning swww-daemon: No such file or directory (os error 2)"`. This also happens when running it from the directory that they're in. I am using the Hyprland compositor on Arch.

**Comment by leozhang1** [comment]
I am having the same issue :'( You're not alone.

**Comment by Blazing-Blast** [comment]
You can get around it by running `swww-daemon` instead of `swww init`. There probably are some caveats, but I haven't had a problem with it yet.

**Comment by lethanix** [comment]
If you add the binaries to the  `$PATH`, make sure to use `$HOME` instead of `~/path/to/bin/swww-daemon`.

That solved the issue for me.

**Comment by LGFae** [comment]
This should no longer be a problem because `swww init` is deprecated. Besides, it was a local user configuration problem anyway.
