### ISSUE TITLE
black screen and and login screen returns

### ISSUE THREAD

**Issue by lucaNobile** [LGFae/swww#160]
Good day everyone , big problem, after an update, my laptop, ( it's an old Asus) started to show me only the black screen.
With the key "super + Q" I used to enter terminal and tried to make some "mess"( otherwise when you learn ?) well now , I get the screen ( I think sddm) login with the request for password , I enter it ( I premise that I tried with the three users on the machine ) and after about 3 seconds it returns to the login screen , passing almost imperceptibly , through a black screen.

**Comment by zer0cha0s** [comment]
Hey, i have been having the same issue this morning, i'm curious if your switch to a different tty (CTRL+ALT+F3 etc) and run `swww init` does it give any errors ?

**Comment by zer0cha0s** [comment]
So i managed to fix mine by changing the hyprland-nvidia-git package to hyprland-nvidia, looks like an update went out yesterday which is causing issues. if your using hyprland-git or hyprland-nvidia-git then trying switching to hyprland or hyprland-nvidia instead.

**Comment by lucaNobile** [comment]
thanks , but my laptop does not have nvidia as it is quite old i have to at this point check what is wron
