### ISSUE TITLE
swww doesn't start in a multi-user setup

### ISSUE THREAD

**Issue by exit91** [LGFae/swww#161]
Current behaviour:
`swww init` won't start the `swww-daemon` if another user is already running `swww-daemon`.

Expected behaviour:
For each available wayland display, an instance of `swww-daemon` can run.
Alternatively: Being able to run one instance of `swww-daemon` per user.

Cause:
The function `is_daemon_running()` ([main.rs]) checks for the existence of a `swww-daemon` instance regardless of the wayland-display it runs on, or even the user that runs it.

Workaround:
Run `swww-daemon` directly to circumvent the check.

[main.rs]: https://github.com/Horus645/swww/blob/517fbeb0f831d43d6c88dac22380536b00e7d9f1/src/main.rs#L370-L398

**Comment by LGFae** [comment]
We are now checking the daemon's existence by trying to ping it at a specified socket, that is different according to the current wayland-display. So this should be fixed. Feel free to reopen this issue if it wasn't.
