### ISSUE TITLE
swww init freezes forever with no error message on arm64 with fractional scaling on

### ISSUE THREAD

**Issue by harbin-ctrl** [LGFae/swww#169]
If I set fractional scaling to 1.5 under sway, and am running on an arm64 system, swww init will freeze forever without error message.  The init does not complete, swww has to be terminated.  swww query shows that the init never completes.

If this configuration is unsupported, an error message should say so, but from reading the other error messages and docs, it seems that swww can work under certain systems using fractional scaling?  It's never exactly clear.

System: Orange Pi 800 wedge computer (4GB RAM, rk3399 chipset)

Edit:  More information:  With whole scaling (1 or 2), swww works fine on the same system.

**Comment by LGFae** [comment]
This is related to, and might be fixed by, #91.

**Comment by LGFae** [comment]
This should be fixed now that we've implemented fractional scaling. I will be closing for now. Feel free to reopen it.
