### ISSUE TITLE
[Feature Request] make swww friendlier to package 

### ISSUE THREAD

**Issue by jsnc-github** [LGFae/swww#174]
Similar to https://github.com/Horus645/swww/issues/172

Hi, I'm currently writing a [package definition](https://codeberg.org/jsnc/SOL/src/branch/main/sol/packages/wm.scm) for `swww` for [GNU Guix](guix.gnu.org/) and currently my package is failing due to the fact that the `utils` dependency does not have a version specified in the project's root `Cargo.toml` file.

> `utils = { path = "utils" }`

The Guix build system for Cargo requires that all dependencies are versioned explicitly within the toml file. 

> `starting phase package' error: all dependencies must have a version specified when packaging.`

via the `cargo package --no-metadata --no-verify` command to create a package tarball.  

I'd highly recommend publishing `swww` onto [crates.io](https://crates.io/) to make the work required to package `swww` far more seamless and to also fix versioning issues.

**Comment by jsnc-github** [comment]
That's totally okay,  but is there any way you can fix the versioning issue with `utils`? I still want to be able to create a crate package from the git repository as that's the only thing currently preventing me from finishing the package.

**Comment by Horus645** [comment]
Ah, just an update, I have fixed the versioning issue. It will land in the next release (should be soon).

I apologize it took me this long for something pretty simple.

**Comment by LGFae** [comment]
Hello, once again I apologize I took so long. Commit `a4c5bdbf08f6ff1839aa76f162f540b822cabca3` fixes this issue with explicit versioning of the `util` crate, so I will be closing this for now.
