### ISSUE TITLE
Don't run in background by default

### ISSUE THREAD

**Issue by WhyNotHugo** [LGFae/swww#182]
By default, `swww` forks and runs as a background process. Every time somebody runs `swww init`, the output of the command is not visible, and killing or restarting the command isn't as simple as <kbd>Ctrl</kbd>+<kbd>c</kbd>. One needs to inspect running processes and figure out which is the right one. There is no obvious indicator of what's going on, and this is especially worse on the first usage of `swww`, where it seems like it's exiting immediately and not really working properly.

This runs contrary to what the gran majority of other commands do: simply run in foreground. If somebody needs to run it in background, popular shells (including `bash`, `zsh`,  and `ksh`) allow simply using `swww init &` to run in background.

Service managers and supervisors also always expect services to run in foreground; demonising like this makes the job of service supervisors a lot harder, since tracking the lifetime of the child doesn't track the lifetime of the service. Eventually the solution is to always  use `swww init --no-daemon`.

I'd like to propose simply running in foreground like any other command and dropping the extra code for daemonisation. For any unique situation where running in background is preferible, using `swww init &` (or maybe `nohup swww init &`) is a trivial workaround.

**Comment by Horus645** [comment]
Interesting proposal. It seems to me like a big breaking change, considering the way we've done things since the beginning. I'll think about it, but I feel like this is a good idea overall.

**Comment by Nemo157** [comment]
A semi-related question: is `swww-daemon` public API? For my systemd service I run that directly instead of going through `swww init --no-daemon` to avoid the extra layering.

**Comment by Horus645** [comment]
Running the daemon directly is currently exactly equivalent to running `init --no-daemon`. I cannot guarantee this will be the case forever, though.

Nevertheless, it would be a breaking change, should it ever change, with big bold letters in the release page.

**Comment by WhyNotHugo** [comment]
Having `swww init` an `swww-daemon` do the same thing is kind of ambiguous.
What do you think of merging both commands into one? Or maybe drop `swww init`?

**Comment by KAGEYAM4** [comment]
> Having `swww init` an `swww-daemon` do the same thing is kind of ambiguous. What do you think of merging both commands into one? Or maybe drop `swww init`?

`man swww-daemon` says this is for debug pupose, and `swww init` should be preffered as it waits for the daemon to be ready.

But i agree the, name and functionality is ambigous unless one looks at the man-page.

**Comment by KAGEYAM4** [comment]
> Since this is already a breaking change, I feel like we should just drop `swww init`. The advantage is that `swww init` will exit immediately without an error.

How about sending a message to stderr stating that `sww init is deprecated` and then in later down the road, `init` it can be totally removed from the argument list.

**Comment by WhyNotHugo** [comment]
There are two potential approaches:

- Drop `swww-daemon` and keep `swww init`: single binary, reduces total installation size.
- Drop `swww init` and keep `swww-daemon`: split client and server logic.

I suppose you've opted for the latter?

**Comment by LGFae** [comment]
> I suppose you've opted for the latter?

Yes. We want the daemon to remain as minimal as possible, because it will run "forever". So I want to put the least amount of burden I can on the users' computers.
