### ISSUE TITLE
Won't Update

### ISSUE THREAD

**Issue by prathameshk23** [LGFae/swww#183]
![image](https://github.com/Horus645/swww/assets/107643856/23fe3141-174d-4cce-ae03-6e25ae6e7eba)
When I try to update it stops with this error

**Comment by vfosterm** [comment]
I'm guessing you have rustup installed, try running rustup update and then attempt upgrade again.

**Comment by Horus645** [comment]
This is a bizarre error, most likely on your end. I can't really help without more information. @vfosterm if probably right.
