### ISSUE TITLE
How can swww be used so that the wallpaper is only applied to the focused monitor?

### ISSUE THREAD

**Issue by TheHyperZtar** [LGFae/swww#184]
Swww is very useful but I would like to know a way for the wallpaper to apply only to the focused monitor because I have 2 monitors and I don't want to have to specify the output

**Comment by Horus645** [comment]
Ah, no, sorry, I don't think so.

You would have to come up with a large command that does everything for you, like so:

```
swww img <path/to/image> --outputs $(<query your window manager for current focused output>)
```

**Comment by TheHyperZtar** [comment]
what would the command be like in hyprland?
