### ISSUE TITLE
GIF transition visual bug

### ISSUE THREAD

**Issue by DADA30000** [LGFae/swww#188]

**Comment by DADA30000** [comment]
https://github.com/Horus645/swww/assets/73874445/5c9287c2-a960-4eac-913d-24bfbc50c7c8

**Comment by Horus645** [comment]
I also just noticed this today. Working on it right now.

**Comment by lucasreis1** [comment]
Hey! I'm seeing this issue too, but after transitions the gif keeps showing bizarre frames and I have to restart the swww daemon for it to work properly.


https://github.com/Horus645/swww/assets/24644129/c593b815-582a-414d-8a94-bde8a6ac935f
