### ISSUE TITLE
Can't pipe animated gifs through stdin

### ISSUE THREAD

**Issue by Nemo157** [LGFae/swww#190]
`cat /tmp/tmp2.gif | swww img --no-resize -` displays just the first frame, while `swww img --no-resize /tmp/tmp2.gif` animates it.

Usecase: I modify the gif with a bit of an imagemagick pipeline before displaying it, I'd prefer not to have to manage temporary files for that if I can just pipe it in instead.

**Comment by Horus645** [comment]
Right, we currently guess the format directly from the file, while for `stdin` we simply default to displaying a still image. Shouldn't be that troublesome to fix.
