### ISSUE TITLE
Error when using the swww-randomize script 

### ISSUE THREAD

**Issue by MRSS02** [LGFae/swww#198]
Sporadically the error `Error: "failed to detect the image's format: Is a directory (os error 21)` appears, even though the directory i passed as an argument has no subdirectories. This is probably because it uses the output of find, and replacing `find "$1"` in the script with `find "$1" -type f` seems to solve the issue.

**Comment by LGFae** [comment]
Thanks. I've pushed your suggestion directly to the main branch.
