### ISSUE TITLE
Running "swww init" throws os error 2.

### ISSUE THREAD

**Issue by birbmotorsports** [LGFae/swww#199]
"WARNING: failed to load cache for output HDMI-A-1: failed to open image: no such file or directory (os error 2)"

This error is thrown whenever I run "swww init" after installing via AUR. Using a SCEPTRE E225W-19208A monitor.

Running on Arch with Hyprland.

**Comment by birbmotorsports** [comment]
Running "swww-daemon" instead successfully initializes swww, but hangs on "Starting main loop..."

**Comment by birbmotorsports** [comment]
@LGFae Could you possibly spare some time to assist me with this?

**Comment by LGFae** [comment]
Hello. Sorry, I am out of town working on a different project right now.

Does this only happen after you install? What happens if you install, init, set a image, shut it down, and then init it again?

**Comment by birbmotorsports** [comment]
> Hello. Sorry, I am out of town working on a different project right now.
> 
> Does this only happen after you install? What happens if you install, init, set a image, shut it down, and then init it again?

What do you mean? It doesn't seem to be initializing at all, from the output given.

**Comment by birbmotorsports** [comment]
![image](https://github.com/LGFae/swww/assets/124483129/d14baf81-2dc1-4c97-b56a-10ae32563351)

**Comment by LGFae** [comment]
That's just a warning, not an error; the daemon should still have been initialized. Try setting an image and see if it runs through. If the daemon didn't initialize, or if it's in an infinite loop, then we have an actual problem.

In any case, please run `swww init` and check with `htop` or something if `swww-daemon` is running. If it is, try setting an image with `swww img`.

**Comment by birbmotorsports** [comment]
![image](https://github.com/LGFae/swww/assets/124483129/154e6d2f-6c54-4f23-a677-4f8a59a3eecc)

Checked if `swww-daemon` was running via `btop`, and it is! :D

And as you can see, it just works. (Photo credits: Škoda Motorsport, Rally Monte Carlo 2019)

Issue will be closed with this comment.

**Comment by birbmotorsports** [comment]
Oh, also, in case you were wondering why I'm in bash in this latest screenshot is because, well basically, I was in the middle of an update and my computer just said `n o` and borked itself. :p
