### ISSUE TITLE
parallax wallpaper feature

### ISSUE THREAD

**Issue by niksingh710** [LGFae/swww#200]
something like on this reddit post https://www.reddit.com/r/unixporn/comments/1acqozr/x11_parralaxx_wallpaper_effect_with_powersaving/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by flick0** [comment]
getting mouse pos can be funky in wayland, so it might not work on all compositors if added

**Comment by LGFae** [comment]
Sorry, this would involve implemented layered wallpapers and is way out of scope for us.
