### ISSUE TITLE
[Bug] Static WebP crash after v0.8.2

### ISSUE THREAD

**Issue by sakarie9** [LGFae/swww#201]
In v0.8.2, attempting to use a static WebP image results in a crash. This issue was not present in v0.8.1.

After some test I believe the problem was introduced by 2ae9eb6, specifically the line of code at

https://github.com/LGFae/swww/blob/a4c5bdbf08f6ff1839aa76f162f540b822cabca3/src/imgproc.rs#L53-L56

which mistakenly treats all WebP images as animated WebP images, then cause the panic at src/imgproc.rs:115

Reproduce
```
swww img '/tmpfs/1.webp'
thread '<unnamed>' panicked at src/imgproc.rs:115:31:
called `Option::unwrap()` on a `None` value
```

WebP info
```
File: 1.webp
RIFF HEADER:
  File size: 392764
Chunk VP8  at offset     12, length 392752
  Width: 3840
  Height: 2160
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
No error detected.
```

**Comment by binarypie** [comment]
I can confirm I also have this same issue on OpenSUSE Tumblelweed swww version 0.8.2

**Comment by LGFae** [comment]
Hello, I have two questions, if you guys could confirm them:

Does this also happen for gifs that are a single image? (for me, it does).

Is the image set despite the crash? (for me, it is).
