### ISSUE TITLE
niri: swww gets stuck in infinite loop with 100% cpu usage

### ISSUE THREAD

**Issue by jeLee6gi** [LGFae/swww#202]
Looks like `swww` does not work with the double buffering implementation in https://github.com/YaLTeR/niri. It manages to draw a single frame on startup before it gets stuck in an infinite loop consuming 100% cpu.

**Comment by YaLTeR** [comment]
To expand on this: swww seems to busyloop here if WlBuffers aren't released right away:

https://github.com/LGFae/swww/blob/a4c5bdbf08f6ff1839aa76f162f540b822cabca3/daemon/src/wallpaper.rs#L168-L180

WlBuffers aren't guaranteed to be released in time for the next frame, and Smithay compositors keep them around for multi-GPU support and, eventually, for GPU reset recovery. Allegedly, sway with the new pixman renderer backend also keeps WlBuffers around.

I'm not sure what swww's requirements are, but it might be possible to fix this by switching to the multi pool: https://smithay.github.io/client-toolkit/smithay_client_toolkit/shm/multi/index.html

**Comment by LGFae** [comment]
I *think* I tried using multi pools before and failed. But `smithay` has changed a lot since, so it might be easier now.

Anyway, thanks for the diagnosis, @YaLTeR !
