### ISSUE TITLE
swww img webp images I get an error

### ISSUE THREAD

**Issue by Ben01233210** [LGFae/swww#213]
```
thread '<unnamed>' panicked at src/imgproc.rs:115:31:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:153:23:
a scoped thread panicked
```

I get this error when I try to add a webp image, I tried multiple. I also restarted the client and rebooted my pc.
I installed swww over pacman. I hope somebody can replicate the issue, if not I will try giving more details.

**Comment by LGFae** [comment]
If you are using the latest release you are probably facing #201. It has already been fixed in the `main` branch.

**Comment by LGFae** [comment]
This is now fixed in the latest release, so I will be closing this.
