### ISSUE TITLE
Graphical glitches throughout half of the wallpaper

### ISSUE THREAD

**Issue by Alawapr** [LGFae/swww#220]
This happens on half of the wallpaper in my main monitor and the entire wallpaper in my secondary monitor

https://github.com/LGFae/swww/assets/93432929/058b4183-fe91-4cec-a7f8-a6ff8840b495

Relevant info: running on Hyprland under Fedora 39 and using an Nvidia card (GTX 1660 SUPER)

**Comment by 0bCdian** [comment]
Having this same issue, and transition glitches on an amd 5300u (vega graphics) so it's definitely not nvidia related.

**Comment by LGFae** [comment]
Just to confirm, in this on 0.8.2 or the latest master?

**Comment by 0bCdian** [comment]
https://github.com/LGFae/swww/assets/101421807/1e8deaa0-2c8b-4db0-93b3-6e431fed9bfd

this is on latest master, the weird glitching happens consistently when trying to set two images a the same time (im calling swww img once for each monitor with different images), this didn't happen on previous versions.

**Comment by Alawapr** [comment]
> Just to confirm, in this on 0.8.2 or the latest master?

as [0bCdian](https://github.com/0bCdian) said and I'm confirming: latest master

**Comment by 0bCdian** [comment]
@LGFae Just informing that I tested your pull request and it fixed the weird glitching. The only visual bug persisting is the jagged lines/glitching in the transition animation, I'll be looking at the changes and testing them 👍🏾
