### ISSUE TITLE
Artefacts during fade transition

### ISSUE THREAD

**Issue by esclear** [LGFae/swww#222]
I'm using swww 0.8.1 in sway.

During a `fade` transition, I see strange artefacts on the screen:
![image](https://github.com/LGFae/swww/assets/7432848/89ccee9b-7d90-4fac-ab47-748d6fe456b0)
These only appear for the duration of the transition and vanish afterwards.
The `simple` transition and others I've tried are not affected.

I suspect that this is not a form of issue #208, as I only have a single connected display:
```
$ swww query
DP-1: 3440x1440, scale: 1, currently displaying: image: /stuff/wallpapers/BigSur.png
```

**Comment by LGFae** [comment]
Just tested, I can confirm the issue on 0.8.1. However, the issue no longer seems to be happening in the latest master. So it appears this was fixed somehow.
