### ISSUE TITLE
Having trouble getting it to work on nixos!

### ISSUE THREAD

**Issue by TheDevConnor** [LGFae/swww#227]
Hello so i came across this and have been trying to get it setup on nixos. I download it through the nixos pkgs, but ever time i run it freezes and does not do anything. Any help is welcomed thank you.

**Comment by LGFae** [comment]
What command are you running? Also can post the output of `swww --version` for me?

**Comment by TheDevConnor** [comment]
but i did get this error
![image](https://github.com/LGFae/swww/assets/99085769/0b44339f-26cf-4bb6-8af8-3a9b8dfc8f79)

**Comment by TheDevConnor** [comment]
NV it works, now. The issue can be closed
