### ISSUE TITLE
[BUG] ReApplying the same image dose not behave same when using command-line-options

### ISSUE THREAD

**Issue by KAGEYAM4** [LGFae/swww#243]
- `swww img <already-applied-image-path>`  -> no or minimum cpu usage ( shows swww skipped applying image because image is same )
- `swww img <already-applied-image-path> --transition-type `  -> high cpu usage ( shows that swww is reapplying the image instead of skipping because image is same)

can we get the same behaviour of `swww img <already-applied-image-path>` in `swww img <already-applied-image-path> --transition-type `.

**Comment by LGFae** [comment]
Actually, we always reapply the same image. The reason you are seeing minimum cpu usage is that the default transition exits very quickly when the images are the same.

I was just writing the code to fix this, but then I realized this will cause trouble when someone overwrites an image. We would have to store the time when we first received the file and then compare it to the file's metadata to make sure the image hasn't changed.

**Comment by LGFae** [comment]
Yet another annoyance: we also need to store the scaling algorithm used. Because setting the same image with `--resize fit` and `--resize crop` is different.

**Comment by KAGEYAM4** [comment]
@LGFae  Do you think this issue/Feature-request should be part of functionality of swww.

The main reason i creating this issue was that i though it was a bug, but now that you have cleared it. I am thinking it will be alot of work for something ( applying the same image ) very rare.

I stumbled upon this because of bug in variety-app, i have a script which calls `variety --pause` when a window is in fullscreen and `variety --resume` when exiting fullscreen. variety was calling `swww` with every call to `variety --pause` and `variety --resume` resulting in high cpu usage where as you state default transition causes minimal cpu usage. So i should be creating/asking on variety wether is this intended feature ( if it is - it sucks )

**Comment by LGFae** [comment]
Does `--pause` and `--resume` just pause animations? If that's the case, we already do that when you go full-screen. But that behavior may change slightly in the future when I try fixing #246.

Alternatively, you can try following #181. That said, I don't think I will implement pausing for `swww` anytime soon.

Regarding this request, I agree with you for now that this seems a little too troublesome for something that won't happen that often. I will close it for the time being.

**Comment by KAGEYAM4** [comment]
> Does `--pause` and `--resume` just pause animations? If that's the case, we already do that when you go full-screen. But that behavior may change slightly in the future when I try fixing #246.

https://github.com/varietywalls/variety downloads jpg/png from wallhaven and other sources and sets them as wallpaper by calling `~/.config/variety/scripts/set_wallpaper` and certain interval. So in fullscreen i didn't wanted to change wallpaper that's why i have a script set up which executes `variety --pause` in fullscreen mode and `variety --resume` when leaving fullscreen mode. It's just that variety is calling `set_wallpaper` with both `variety --pause` and `variety --resume`. It might be a bug.

**Comment by KAGEYAM4** [comment]
Also, i wanted to ask, are there some wayland protocol/API which helps detect if fullScreen Mode is on? Then i would ask variety dev to implement it to automatically pause variety on fullScreen mode.

**Comment by LGFae** [comment]
I honestly don't know. I looked it up some time ago and couldn't find anything.
