### ISSUE TITLE
crash coredumped in 0.9.1 (swww-daemon)

### ISSUE THREAD

**Issue by n1ckisthereu** [LGFae/swww#244]
i upgraded my swww to the last version, but if i try change my wallpaper, it crash

![image](https://github.com/LGFae/swww/assets/75399141/de7f44ca-1b3f-4643-955a-3dc091216e08)

**Comment by LGFae** [comment]
This was already fixed in the latest master, try using that instead.

**Comment by LGFae** [comment]
Now that we've published version 0.9.2, I will be closing this.
