### ISSUE TITLE
Wallpaper bug: Wallpaper is greyscale & 30 deg rotated(using hyprland)

### ISSUE THREAD

**Issue by N0CTRON** [LGFae/swww#245]
I use:
- Hyprland on Fedora 39.
- A Fujitsu Laptop[Fujitsu Lifebook E, i5 @2.4GHz]
- Other system specs(if its helpful:)):
-   -16GB RAM(Added 8GB trought modification on the motherboard)
-   -No Graphics card(only integrated, Skylake GT / i5 HD Graphics 520).
-   - Standart Monitor.
-   - Undervolted cache & core by -20. (--undervolt --core -20 --cache -20)

- How I installed swww:
-    - It came preinstalled with Hyprland. I installed Hyprland trought the GitHub repo.

- What I tried:
-   - swww -kill
-   - swww -clear
-   Errors I got:
[root@fedora ~]# swww clear
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww kill
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww-daemon
thread 'main' panicked at daemon/src/main.rs:129:45:
failed to connect to the wayland server: NoCompositor
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
20:49:06 [INFO] (main) Removed socket at "/tmp/swww/swww.socket"
[root@fedora ~]# swww init
DEPRECATION WARNING: `swww init` IS DEPRECATED. Call `swww-daemon` directly instead
Error: "There seems to already be another instance running..."

 I think I'm just dumb or smth, bug I read all the other issues(f.e: "Wallpaper show distorted and in grayscale #233") and found mine still not getting resolved, even in a similar issue, so please be patient with me.

I tried taking some screenshot, but it didn't work. Im new to Linux and probaly take some time to learn all this, but I can provide you with the console output:

[root@fedora ~]# swww
A Solution to your Wayland Wallpaper Woes

Usage: swww <COMMAND>

Commands:
  clear        Fills the specified outputs with the given color
  restore      Restores the last displayed image on the specified outputs
  clear-cache  Clears the swww cache
  img          Sends an image (or animated gif) for the daemon to display
  init         Initializes the daemon
  kill         Kills the daemon
  query        Asks the daemon to print output information (names and dimensions)
  help         Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help (see more with '--help')
  -V, --version  Print version
[root@fedora ~]# swww clear
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww restore
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww clear-cache
[root@fedora ~]# swww kill
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww init
DEPRECATION WARNING: `swww init` IS DEPRECATED. Call `swww-daemon` directly instead
Error: "There seems to already be another instance running..."
[root@fedora ~]# swww query
Error: "Socket file not found. Are you sure swww-daemon is running?"
[root@fedora ~]# swww-daemon
thread 'main' panicked at daemon/src/main.rs:129:45:
failed to connect to the wayland server: NoCompositor
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
21:01:04 [INFO] (main) Removed socket at "/tmp/swww/swww.socket"

The Wallpaper currently has the same issue as opened here, but the solutions didn't work for me: https://github.com/LGFae/swww/issues/233

**Comment by Senshi111** [comment]
same here on fedora and ubuntu

**Comment by myamusashi** [comment]
Same on Arch

**Comment by Shuvlyy** [comment]
Same on Arch

**Comment by myamusashi** [comment]
Solution for now
 swww-daemon --format xrgb

**Comment by Senshi111** [comment]
Can someone try and change swww init to swww-daemon --format xrgb

**Comment by Shuvlyy** [comment]
> Can someone try and change swww init to swww-daemon --format xrgb

It works.
![240324_23h06m06s_screenshot](https://github.com/LGFae/swww/assets/123988037/4ee47e2a-7d62-4cec-a40f-601ac895b04c)

**Comment by LGFae** [comment]
Everyone, go to issue #233. That's the exact same problem, with the exact workaround @Senshi111 pointed out.

@N0CTRON, you have a different problem. From what  you've posted, you've tried using `swww` wrong. Try this:

In terminal 1, run:

```
swww-daemon
```

In terminal 2, run:

```
swww img <some-img>
```

See if it works. It it's grayscale, stop the daemon and start it with

```
swww-daemon --format xrgb
```

And try again.

**Comment by myamusashi** [comment]
Don't use "swww init", it's Deprecated #238

**Comment by LGFae** [comment]
Incidentally, is everyone who's having problems here, on laptops?

**Comment by N0CTRON** [comment]
> Everyone, go to issue #233. That's the exact same problem, with the exact workaround @Senshi111 pointed out.
> 
> @N0CTRON, you have a different problem. From what  you've posted, you've tried using `swww` wrong. Try this:
> 
> In terminal 1, run:
> 
> ```
> swww-daemon
> ```
> 
> In terminal 2, run:
> 
> ```
> swww img <some-img>
> ```
> 
> See if it works. It it's grayscale, stop the daemon and start it with
> 
> ```
> swww-daemon --format xrgb
> ```
> 
> And try again.

It worked, but I had to switch to the standard "xf" from the login screen. Seems like it's a bug shared with hyprland. Thanks for the straightforward and fast reply!!
