### ISSUE TITLE
the wallpaper becomes black and white and fuzzy 

### ISSUE THREAD

**Issue by antkss** [LGFae/swww#249]
![image](https://github.com/LGFae/swww/assets/88892713/e9eda797-24e0-462c-aec2-0cb6de423028)

**Comment by notLonelySoul** [comment]
You should have taken a look at #233 

Anyways, i see that u are using end-4's dotfiles. You can fix it by going to `~/.config/hypr/hyprland/execs.conf` and changing the first line from 
```exec-once = swww kill; swww init```
to 
```exec-once = swww kill; swww-daemon --format xrgb```

then log-out and log-in to see the changes.

**Comment by antkss** [comment]
thank you for your support, it's worked fine 
![image](https://github.com/LGFae/swww/assets/88892713/0694de25-2e1b-4df6-a325-68646b3b69f2)
