### ISSUE TITLE
High CPU usage with animations

### ISSUE THREAD

**Issue by Ay1tsMe** [LGFae/swww#259]
When changing my wallpaper using animations, the CPU usage is at 100 percent during the animation. The animation also seems to drop frame rate due to the high load. Is this normal? I don't remember seeing this kind of behaviour on previous versions. I was using v0.8.2 before i updated to v0.9.1 and that's where I've noticed the change.

**Comment by LGFae** [comment]
Which animation specifically are you talking about? `simple`?

**Comment by Meisaki** [comment]
i am also having similar problem i does not have same problem ,but they are in a way similar my first two core out of 4 get full usage whenever swww change wallpaper , about animation you asked i use default one it appear like fade if you know what i mean  about system i use arch hyprland(git version)

**Comment by Ay1tsMe** [comment]
> Which animation specifically are you talking about? `simple`?

I'm using the `wipe` transition set at 144 fps. This is the command:
```
swww img "$IMAGE" -t wipe --transition-fps=144
```

I tried with the `simple` animation and there is no high cpu usage.

**Comment by Meisaki** [comment]
So I tried removing yay cache of swww-git then reinstall swww-git guess what it work like that is use to be but there one problem now again whenever I play game (wine) when I exit game sometime or heavy game time I see wallpaper as blur, glitch, distorted for about 5-10 seconds then it go away
