### ISSUE TITLE
FreeBSD 14 build error complains no sa_restorer

### ISSUE THREAD

**Issue by Canvis-Me** [LGFae/swww#261]
When ran `cargo build --release`, it showed

```
error[E0560]: struct `sigaction` has no field named `sa_restorer`
   --> daemon/src/main.rs:205:9
    |
205 |         sa_restorer: None,
    |         ^^^^^^^^^^^ `sigaction` does not have this field
    |
    = note: all struct fields are already assigned

For more information about this error, try `rustc --explain E0560`.
error: could not compile `swww-daemon` (bin "swww-daemon") due to 1 previous error
```

It seems `FreeBSD` has different definition of `sigaction` according to https://man.freebsd.org/cgi/man.cgi?sigaction

**Comment by LGFae** [comment]
As I don't have a `FreeBSD` system, could you try compiling PR #265 to see if it works now?

**Comment by Canvis-Me** [comment]
Branch [sigaction-on-freebsd](https://github.com/LGFae/swww/tree/sigaction-on-freebsd) works well, thank you.
