### ISSUE TITLE
Daemon doesn't remove swww.socket file when closed in a certain way.

### ISSUE THREAD

**Issue by MisterZig** [LGFae/swww#262]
Disclaimer: I don't know much about how daemons work and how exactly they are meant to function.

I ran the `swww-daemon` command and then I realized that it it stayed open in my terminal so I wanted to close it and run it in the background, so pressed CTRL+C  which worked. I then restarted it with `swww-daemon &` which still left me without another prompt. When I pressed CTRL+C again the daemon stayed open and I could run other commands, but when I closed my terminal emulator the daemon closed and the swww.socket file wasn't removed.

```
$ swww-daemon &
[1] 4446
[me@zzz ~]$ 09:07:29 [INFO] (main) Initialization succeeded! Starting main loop...
09:07:29 [INFO] (main) Selected wl_shm format: Bgr888
09:07:29 [INFO] (transition) BumpPool with: 2 buffers. Size: 86400Kb
09:07:29 [INFO] (transition) BumpPool with: 2 buffers. Size: 86400Kb
^C
[me@zzz ~]$ 
```

Kitty (my terminal emulator) also didn't note that anything was running when I tried to kill it. Normally when I'm running a program it prompts me if I'm sure.

I'm running endeavourOS with the 6.8.2.arch2-1 Kernel and Hyprland.
Output of `pacman -Q swww hyprland`
swww 0.9.1-1
hyprland 0.38.0-1
Output of `swww-daemon -V`
swww-daemon 0.9.1

I've been able to reproduce this multiple times by just removing the socket file and restarting the daemon in a new terminal.

To me it would make sense that the daemon is just getting a different signal than the one given by a keyboard interrupt so the daemon doesn't run the same procedure to close gracefully.
If someone knows what signal would be sent I'd be happy to try to fix this bug myself. I'm pretty sure it hasn't got to do with the fact that I'm running it with the & since if I kill it with a SIGTERM using htop it does still remove the swww.socket file. I do believe it is possible that it's a problem with kitty but I thought I'd check here first. If anyone does know what signal is sent, I'd love to learn how to find that out myself.

**Comment by LGFae** [comment]
From a quick research, it seems to be SIGHUP.

**Comment by LGFae** [comment]
If you are interested in fixing this, you just need to edit here: https://github.com/LGFae/swww/blob/main/daemon/src/main.rs#L208

**Comment by LGFae** [comment]
Commit https://github.com/LGFae/swww/commit/c77cdff1a7a9653339041ca1f49bd8fbe886f676 fixed this.
