### ISSUE TITLE
Where do I put compiled files on Ubuntu 23.10

### ISSUE THREAD

**Issue by gungugugungu** [LGFae/swww#264]
Hi! I recently installed Hyprland on my pc with Ubuntu 23.10, but I saw that I didn't have wallpapers, so I wanted to install swww to fix it. When I finished compiling, I moved the files basically everywhere, hoping it'll work. I moved them to each path in the PATH environment variable, each manpath, rebooted, and nothing happened. How can I make this work?

**Comment by LGFae** [comment]
what's the output of `echo $PATH`? Move `swww` and `swww-daemon` to one of those directories.

**Comment by gungugugungu** [comment]
oooh, I get it. I was moving the /doc/generated files to the $PATH places. It works now
