### ISSUE TITLE
Output selection is broken on latest master

### ISSUE THREAD

**Issue by 0bCdian** [LGFae/swww#269]
--outputs option is currently broken on latest git.

https://github.com/LGFae/swww/assets/101421807/685773e7-5a14-4b93-a40c-e51023473384

I'm sorry for submitting issues frequently,  I have project that depends entirely on swww. I'm currently learning rust to be able to contribute but for now all I can do is submit issues as soon as I find them. Thanks for this awesome tool!

**Comment by wcq062821** [comment]
You should replace "swww init" with "swww-daemon".

**Comment by 0bCdian** [comment]
> You should replace "swww init" with "swww-daemon".

I was already doing that.

https://github.com/LGFae/swww/assets/101421807/cfa8b5ac-f07e-4d69-8347-852631620500

**Comment by LGFae** [comment]
Fixed by commit https://github.com/LGFae/swww/commit/3a3596c3b22740086f18ffb6b02aa89ef26a04fe.

> I'm sorry for submitting issues frequently, I have project that depends entirely on swww.

Don't worry about that; it's better to catch these things are early as possible! If anything, I'm thankful :smiley:

**Comment by LGFae** [comment]
> probably the culprit is wl_output from the wayland server protocol 

No no, the problem was entirely on us. If you look at the commit, all that did was change one line. From:
```rust
self.inner_staging.lock().unwrap().name = Some(desc)
```
to:
```rust
self.inner_staging.lock().unwrap().desc = Some(desc)
```

In other words, I was wrongly overwriting the output's name with its description.

**Comment by 0bCdian** [comment]
Oh I see, anyway thanks again for the quick fix!
