### ISSUE TITLE
I couldn't run sww-daemon

### ISSUE THREAD

**Issue by hasansarikaya94** [LGFae/swww#271]
Hi everyone, 

I compiled it successfully.

However, when I want to run it, I get an error as follows. How can I run it?

thread 'main' panicked at daemon/src/main.rs:323:14:
layer shell is not available: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
13:57:46 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"

![Screenshot from 2024-04-09 17-03-19](https://github.com/LGFae/swww/assets/58563477/fd3920f7-fb40-44da-888d-86f49f34828a)

![Screenshot from 2024-04-09 17-14-52](https://github.com/LGFae/swww/assets/58563477/b8f32cea-1e8a-4dd2-9d31-baae30cc1b02)

**Comment by LGFae** [comment]
Gnome does not implement the `wlr-layer-shell` protocol, which is necessary to run `swww`.

I am afraid the only fix would be changing your window manager to one that does implement the protocol. There's sway, hyprland, I think even KDE. I don't know how feasible it is to do that in Fedora, however.
