### ISSUE TITLE
Allow running in nested Wayland sessions

### ISSUE THREAD

**Issue by Fuyukai** [LGFae/swww#272]
If you run a nested Wayland WM, then try running ``swww-daemon`` inside that one, it'll try and rebind to the socket that an outer instance is using. 

I think the easiest way to implement this would be to make the socket filename `swww-$WAYLAND_DISPLAY.socket`. 

I understand if this isn't in-scope for the project, but if it is, I'm willing to implement it myself.

**Comment by LGFae** [comment]
> I understand if this isn't in-scope for the project, but if it is, I'm willing to implement it myself.

You can go ahead, if you want!
