### ISSUE TITLE
Uninstall from source

### ISSUE THREAD

**Issue by cristiangrossano** [LGFae/swww#274]
I don't have much experience with cargo source build. How can I uninstall swww?

Could you please ad a section in the readme about this?

**Comment by LGFae** [comment]
To uninstall `swww` either do it through your package manager, or, if you installed manually, simply remove `swww`  and `swww-daemon` from your `$PATH`. You can then simply delete the directory with the source files.

This is pretty standard stuff. The way to uninstall depends on how you installed it first. If you went through the trouble of manually downloading the sources, compiling them, and adding them to your `$PATH`, I expect you to know how to remove all that. There's nothing particularly special about cargo that would make it different from any project you did these things.
