### ISSUE TITLE
issues with swww v0.9.2 about resize "fit" option

### ISSUE THREAD

**Issue by random2907** [LGFae/swww#279]
v0.9.1

![image](https://github.com/LGFae/swww/assets/81547183/72cb015f-2d51-49ad-b9be-5333597cb1f3)

v0.9.2

![image](https://github.com/LGFae/swww/assets/81547183/f9e5dc54-a934-4574-8d6b-80f27bfbb679)

**Comment by LGFae** [comment]
I need more info. What's the monitor's resolution and the image's size?

**Comment by random2907** [comment]
> I need more info. What's the monitor's resolution and the image's size?

 PNG image data, 1920 x 1080, 8-bit/color RGBA, non-interlaced


➜  ~ swww query
eDP-1: 1280x720, scale: 2, currently displaying: image: /home/ranjeet/.wallpapers/wallhaven-5dmxg8.png
➜  ~ hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1080@60.00300 at 0x0
	description: BOE 0x09AE
	make: BOE
	model: 0x09AE
	serial:
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.50
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz

**Comment by LGFae** [comment]
This is a scaling problem. `swww-daemon` is trying to render that image as if the monitor were `2560x1440`.

**Comment by LGFae** [comment]
Since this could affect a lot of people, I decided to do a small release immediately. Thanks for the report!

**Comment by random2907** [comment]
for me its not fixed it now not scale no resize option is doing anything its like not scale its fixes when i set my scaling to 1. 

![image](https://github.com/LGFae/swww/assets/81547183/da0442f8-6214-4106-9439-bf345ddef7c5)

**Comment by random2907** [comment]
> Since this could affect a lot of people, I decided to do a small release immediately. Thanks for the report!

for me its not fixed it now not scale no resize option is doing anything its like not scale its fixes when i set my scaling to 1. 

![image](https://github.com/LGFae/swww/assets/81547183/da0442f8-6214-4106-9439-bf345ddef7c5)

**Comment by LGFae** [comment]
> for me its not fixed it now not scale no resize option is doing anything its like not scale its fixes when i set my scaling to 1

I'm sorry, I cannot fully understand this sentence. Have you tried the latest version, `0.9.3`, with `--no-resize` option? Is that it?

**Comment by random2907** [comment]
> > for me its not fixed it now not scale no resize option is doing anything its like not scale its fixes when i set my scaling to 1
> 
> I'm sorry, I cannot fully understand this sentence. Have you tried the latest version, `0.9.3`, with `--no-resize` option? Is that it?

yes i am using v0.9.2

i mean that its now not even resizing 
this is the swww query now.
eDP-1: 960x540, scale: 2,

**Comment by LGFae** [comment]
Hmm... this should be consistent with the previous behavior though. Well, in any case, we are reopening this.

**Comment by Akira-uestc** [comment]
swww v0.9.3
WM:hyprland
❯ swww query                          
eDP-1: 960x540, scale: 2, currently displaying: image: /home/akira/Pictures/pixel/IMG_20231031_172210_589.png
❯ hyprctl monitors   
Monitor eDP-1 (ID 0):
	1920x1080@60.00000 at 0x0
	description: BOE 0x0936
	make: BOE
	model: 0x0936
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 45 0 0
	scale: 1.25
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz 1920x1080@48.00Hz

When not using integer scale, swww cannot tile to full screen
![18323324AB0EFFFB28BEB7C77924E5D4](https://github.com/LGFae/swww/assets/124018024/60cfe595-f543-4a49-b5de-fb1019b254e8)

**Comment by hdm9527** [comment]
After upgrade swww to v0.9.3 encountered the same problem. Swww v0.9.2 scaling is correct.
![image](https://github.com/LGFae/swww/assets/39702328/61d7507c-11ea-4937-b6a7-33dc39da31c9)

**Comment by LGFae** [comment]
Wait, @Akira-uestc, @hdm9527, is that happening with the default settings? As in, you just call `swww img <picture` and that's what happens? Or are you calling it with `--no-resize`?

**Comment by zzucch** [comment]
Same here, --no-resize does not help.

swww 0.9.3, hyprland 0.38.1

![image](https://github.com/LGFae/swww/assets/112894483/859422d2-5415-47ed-8964-08818b6d3c9c)


```
$ swww query
eDP-1: 960x540, scale: 2, currently displaying: image: /home/zcchr/walls/black.jpg
```

```
$ hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1080@60.00000 at 0x0
	description: BOE 0x092E
	make: BOE
	model: 0x092E
	serial: 
	active workspace: 4 (4)
	special workspace: 0 ()
	reserved: 0 28 0 0
	scale: 1.25
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz 1920x1080@48.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz
```

```
$ file ~/walls/black.jpg 
/home/zcchr/walls/black.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 99", baseline, precision 8, 1920x1080, components 3
```

**Comment by itsmenewbie03** [comment]
> Same here, --no-resize does not help.
> 
> swww 0.9.3, hyprland 0.38.1
> 
> ![image](https://private-user-images.githubusercontent.com/112894483/322627969-859422d2-5415-47ed-8964-08818b6d3c9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjY0MDUsIm5iZiI6MTcxMzI2NjEwNSwicGF0aCI6Ii8xMTI4OTQ0ODMvMzIyNjI3OTY5LTg1OTQyMmQyLTU0MTUtNDdlZC04OTY0LTA4ODE4YjZkM2M5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzUyZTRjNGU1NDNhOTIzM2UwOTNhN2YxZWFkYzJjYjVkYmNiM2QyNjE3ODhkYWNmYmM5NjViYjBkODMxMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYA9NbYzNE7HcAvDWhEa9hr6dTpuSyb6xWdRBAoYHSA)
> 
> ```
> $ swww query
> eDP-1: 960x540, scale: 2, currently displaying: image: /home/zcchr/walls/black.jpg
> ```
> 
> ```
> $ hyprctl monitors
> Monitor eDP-1 (ID 0):
> 	1920x1080@60.00000 at 0x0
> 	description: BOE 0x092E
> 	make: BOE
> 	model: 0x092E
> 	serial: 
> 	active workspace: 4 (4)
> 	special workspace: 0 ()
> 	reserved: 0 28 0 0
> 	scale: 1.25
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> 	activelyTearing: false
> 	currentFormat: XRGB8888
> 	availableModes: 1920x1080@60.00Hz 1920x1080@48.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz
> ```
> 
> ```
> $ file ~/walls/black.jpg 
> /home/zcchr/walls/black.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 99", baseline, precision 8, 1920x1080, components 3
> ```

experiencing the same

**Comment by heltechael** [comment]
> > Same here, --no-resize does not help.
> > swww 0.9.3, hyprland 0.38.1
> > ![image](https://private-user-images.githubusercontent.com/112894483/322627969-859422d2-5415-47ed-8964-08818b6d3c9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjY0MDUsIm5iZiI6MTcxMzI2NjEwNSwicGF0aCI6Ii8xMTI4OTQ0ODMvMzIyNjI3OTY5LTg1OTQyMmQyLTU0MTUtNDdlZC04OTY0LTA4ODE4YjZkM2M5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzUyZTRjNGU1NDNhOTIzM2UwOTNhN2YxZWFkYzJjYjVkYmNiM2QyNjE3ODhkYWNmYmM5NjViYjBkODMxMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RYA9NbYzNE7HcAvDWhEa9hr6dTpuSyb6xWdRBAoYHSA)
> > ```
> > $ swww query
> > eDP-1: 960x540, scale: 2, currently displaying: image: /home/zcchr/walls/black.jpg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > $ hyprctl monitors
> > Monitor eDP-1 (ID 0):
> > 	1920x1080@60.00000 at 0x0
> > 	description: BOE 0x092E
> > 	make: BOE
> > 	model: 0x092E
> > 	serial: 
> > 	active workspace: 4 (4)
> > 	special workspace: 0 ()
> > 	reserved: 0 28 0 0
> > 	scale: 1.25
> > 	transform: 0
> > 	focused: yes
> > 	dpmsStatus: 1
> > 	vrr: 0
> > 	activelyTearing: false
> > 	currentFormat: XRGB8888
> > 	availableModes: 1920x1080@60.00Hz 1920x1080@48.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > $ file ~/walls/black.jpg 
> > /home/zcchr/walls/black.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, comment: "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 99", baseline, precision 8, 1920x1080, components 3
> > ```
> 
> experiencing the same

Also experiencing this when using Hyprland monitor config: `monitor=,1920x1080@60,auto,1.25`. Resizing the image by multiplying the fractional scale before sending it through `swww` did not work for me either. I tried:
- Monitor resolution: 1920x1200
- Original image size: 1920x1080
- Resized image size: 2400x1500 (monitor res times 1.25)

**Comment by LGFae** [comment]
Oh, right, sorry. This is a fundamental problem of the surface size we are using. It's just going to break every time. There is no workaround actually.

**Comment by LGFae** [comment]
> why no downgrade option you should at least keep 5 to 10 version

Downgrade isn't controlled by me. All the previous versions are still there. Downgrading must be supported either by your package manager, or you must do it yourself if you compiled manually.

**Comment by azurstar** [comment]
> > Oh, right, sorry. This is a fundamental problem of the surface size we are using. It's just going to break every time. There is no workaround actually.
> 
> why no downgrade option you should at least keep 5 to 10 version

you can downgrage to 0.8.2 by AUR.
```
git clone https://aur.archlinux.org/swww.git && cd swww
git reset --hard f5971656d37d7ded2e803f9655685c416ca6b71e
paru -Ui
```

**Comment by zzucch** [comment]
> PR #282 should fix this. I've tested under sway over here in my setup. Can anyone confirm me it works? (or doesn't)

It resolved the issue for me, thanks.

**Comment by heltechael** [comment]
I can confirm that it works for me, @LGFae! Thank you for your excellent work.
