### ISSUE TITLE
Swww crashing when switching the wallpaper image.

### ISSUE THREAD

**Issue by Oglo12** [LGFae/swww#283]
When I switch my wallpaper image, Swww has a 80% chance or so of just crashing. When I try to start it back up, it gives me an address in use os error 98 error.
![image](https://github.com/LGFae/swww/assets/80219532/8d45256a-368c-4d09-a286-59efcd5e65c6)

Idk if it matters, but I am on Hyprland.

Swww Version: 0.9.1

**Comment by LGFae** [comment]
Try using the latest git version instead.

**Comment by Oglo12** [comment]
It works now, thank you!
