### ISSUE TITLE
v0.9.3 broke resizing of wallapapers

### ISSUE THREAD

**Issue by nyadiia** [LGFae/swww#284]
this seems like the same thing that was happening in #279 except none of the options talked about in there have worked. 
![image](https://github.com/LGFae/swww/assets/43252360/7da58899-d0a0-4725-84b6-160c91308ccb)
the issue goes away if i use a non fractional scale ( like 1 or 2 ). i'm on the latest tagged hyprland release ( 0.39.1 ) and the latest tagged swww release ( 0.9.3-1 ) and i'm on arch.

**Comment by LGFae** [comment]
The latest release is 0.9.4. If you are on arch, try getting the `git` version from the AUR. That should fix this.

**Comment by nyadiia** [comment]
i see, did not check the latest release version and assumed the aur was up to date already, sorry! `-git` works and well
