### ISSUE TITLE
[Feature request] add hyprland splash render

### ISSUE THREAD

**Issue by LOSEARDES77** [LGFae/swww#288]
Hyprland has a "splash" wich is a short text ramdomly choosed at start and it would be nice to have it render this at the wallpaper centered on the bottom in hyprpaper this is done usin cairo for rendering text.
This can be done by deteccting in you are on hyprland and the used added an special cli arg or something to enable this.
The way of getting the splash text is throw executing a command `hyprctl splash` and it return the splash.

**Comment by LGFae** [comment]
Sorry, I consider this to be entirely out of scope for this project. I have no interest in adding things that are specific for this or that compositor, and text rendering in particular is quite annoying.
