### ISSUE TITLE
swww crashed itself and sway

### ISSUE THREAD

**Issue by Qinka** [LGFae/swww#293]
swww version is `0.9.4`

* multi screen:
```
output DP-1 mode "3440x1440@190Hz"
output DP-1 pos 0 0
output DP-3 transform "270"
output DP-3 pos 3440 100
output HDMI-A-3 pos 900 1440
output HDMI-A-3 transform "180"
output HDMI-A-3 scale 1.5
```

The output of HDMI-A-3 is wrong:
![2024-04-25T11:01:40,275356719+08:00](https://github.com/LGFae/swww/assets/9249996/d289135f-7518-4215-a1c2-8ae51562d507)

when I executed `swww img --resize crop -t none -o HDMI-A-3 6.jpg`
swww and sway is crashed.

The log of dmesg I listed in https://github.com/swaywm/sway/issues/8133 

SO DO I : https://github.com/LGFae/swww/issues/275

**Comment by Qinka** [comment]
I rolled back the version to 0.9.1 and that fixed the problem, and Sway and SWWW don't crash anymore.

**Comment by Qinka** [comment]
@AhJi26  This is correct:

![2024-04-25T20:34:33,564072800+08:00](https://github.com/LGFae/swww/assets/9249996/d935e24f-0a17-45eb-8cd0-d5cc53353677)

**Comment by LGFae** [comment]
Try the latest master instead of 0.9.4. See if this issue persists.

**Comment by Qinka** [comment]
@LGFae  It's not crashing anymore and the display is normal.

**Comment by Qinka** [comment]
@LGFae 
Sorry, it wasn't resolved. The output is still wrong. The background should be a colorful image.
![2024-05-02T14:28:44,317769967+08:00](https://github.com/LGFae/swww/assets/9249996/3610b9d2-cf30-43fd-9d48-059d0cc64ac3)

**Comment by LGFae** [comment]
In that case, try `swww-daemon --format xrgb`. It should at least serve as a workaround.

**Comment by Qinka** [comment]
> In that case, try `swww-daemon --format xrgb`. It should at least serve as a workaround.

main branch and v0.9.5 solved my problem.
 
> EDIT: ah, looking at dmesg, it seems you are on nvidia. This might have something to so with it...

My GPU is Intel Arc A770
