### ISSUE TITLE
v0.9.5 still doesn't work properly with transforms

### ISSUE THREAD

**Issue by grudgingly** [LGFae/swww#300]
Version 0.9.5 behaves the same as 0.9.4 on my GPD Pocket (v1), cropping the image portrait and then projecting it wrongly onto the landscape screen. v0.9.1 works correctly.

For background, this computer has at first glance a 1920x1200 7" landscape screen, but it's actually a 1200x1920 portrait display (intended for tablets) that's installed sideways. This is very common on recent small "netbook"-type machines as the portrait displays are much easier to source. The Linux kernel detects known cases and automatically applies rotation in KMS, which Wayland picks up.

Screenshot attached showing behaviour with the "Silhouette of Skyway" example from the readme, along with the output of `wlr-randr`. The compositor is Wayfire and the OS is Arch Linux.

![20240503_16h05m01s_grim](https://github.com/LGFae/swww/assets/47045857/a3911181-bd5b-43ef-964c-28ad49a94b83)

**Comment by LGFae** [comment]
Ah, I see. Here's what's happening: 

  * Because the output is rotated 270 degrees, we set `vertical` to true.
  * Because `vertical` is true, we set the height to be the larger value between 1200 and 1920, and the width to be the smaller one.
  * We try to render it, and it looks wrong, because the monitor is actually horizontal.

**Comment by LGFae** [comment]
Actually, turns out we have a problem that's a little more annoying: `swww` handles transforms during execution incorrectly. For example, if start `swww` with the normal transform and then try to change it 90 degrees, it doesn't work.

**Comment by LGFae** [comment]
Could you test #301 yourself, just to be sure? It seems to work over here.

Note that, to test it properly, you need to do `swww-daemon --no-cache`, because the daemon will try to fire the `swww` client currently in your path when loading the cache, and that one has a different IPC setup.

**Comment by grudgingly** [comment]
Works beautifully! Thank you for the fast response!
