### ISSUE TITLE
Transition postitions seem to be inverted

### ISSUE THREAD

**Issue by 0bCdian** [LGFae/swww#307]
When using the --transition-pos flag and using the aliases, like top-right/bottom-right  the y axis is inverted, so bottom-right puts the circle in the top  and vice-versa.

this is the command I'm using 

```bash
swww img "$IMAGE" --outputs eDP-1,HDMI-A-1, --resize="crop" --fill-color "#000000" --filter Lanczos3 --transition-type grow --transition-step 255 --transition-duration 1.7 --transition-fps 60 --transition-angle 45 --transition-pos top-right  --transition-bezier .43,1,.19,.4 --transition-wave "20,20"
```
             

https://github.com/LGFae/swww/assets/101421807/96446542-a6af-43fb-8f9a-89d182544196

I don't know since when this has been occurring,  I'm on the latest git. Thanks in advance!

**Comment by LGFae** [comment]
Fixed by commit 90e9553
