### ISSUE TITLE
images look horribly wrong when set as wallpapers in all image formats including gif

### ISSUE THREAD

**Issue by I-like-stuff** [LGFae/swww#314]
images look weird, they appear in black and white and are stretched apart from the fact that transitioning to a different wallpaper end up crashing my PC, here are examples 
 
this is the wallpaper: 
![4k-ai-mountain](https://github.com/LGFae/swww/assets/109248186/f310c6cc-39d1-4af5-8d8d-619b5c354977)
and this is how it looks like:
![image](https://github.com/LGFae/swww/assets/109248186/59ae2999-ea20-4379-be95-29aad5e1a167)

and this applies to all images, including gif images 
I'm running Nixos Unstable and running the swww from the flakes, meaning that I should be running the latest upstream version

**Comment by LGFae** [comment]
try starting the daemon with `swww-daemon --format xrgb`.

By the way, do you have an integrated display (like in a notebook)?

**Comment by I-like-stuff** [comment]
weird that I now have to use ``swww-daemon --format xrgb`` in order to have the wallpapers displayed correctly but whatever, it is working, wallpapers are being displayed with the correct color formatting.
and no I am not running integrated graphics, my machine runs with an rx 6500xt and the cpu I'm using don't have integrated graphics

**Comment by LGFae** [comment]
Huh. That *is* interesting actually. Previously this would happen primarily on integrated displays (see #303).

I think this is a Mesa bug actually, but since I don't seem to have any hardware where this problem arises, I can't confirm it. 

I will this open for now to remind me to add `--format xrgb` to the README, since a lot of people have been reporting more or less the same issue.

**Comment by I-like-stuff** [comment]
Almost all the problems are now fixed with the ``--format xrgb`` command, I even set it as a startup command in my hyprland config, might as well just add it in the README for those who are facing the issue, now thanks for helping..

**Comment by LGFae** [comment]
This is already in the `README`, actually. It is the first entry in the troubleshooting section. So I guess I will be closing this.
