### ISSUE TITLE
Animated wallpapers (gif) lead to Desktop stutter/lag

### ISSUE THREAD

**Issue by yungcxn** [LGFae/swww#320]
Is there anybody experiencing similar issues? 
The performance/ driver setup of my pc is not the issue, it occured recently without any change in my setup.

**Comment by LGFae** [comment]
Are you sure you didn't update anything? Because, if nothing changed, then this is rather strange.

Otherwise, are you on 0.9.5 or the latest git version?

**Comment by yungcxn** [comment]
Oh sorry, my mistake. I forgot. I updated my NVIDIA driver from 525 to 555 and I am not on the git version

**Comment by yungcxn** [comment]
This is fixed on the git branch
