### ISSUE TITLE
Black screen after login

### ISSUE THREAD

**Issue by DataHearth** [LGFae/swww#332]
Hello there!

I've updated `swww` from `0.8.2` to `0.9.5` yesterday, but now I encounter a problem (which seems to have be resolved and merge into the latest release but still occurs for me) with a black screen on login with a scaling monitor. I've never had this problem before and only occurs on one of my display (`DP-2` which is 4k display scaled to `2` for visibility).

Anyway I can fix this?

Thank!

My setup:
OS: NixOS - Nixpkgs unstable
DE: Hyprland `v0.41.1`
swww: `0.9.5`
Monitors: 
- HDMI-A-1: 1920x1080, scale: 1, currently displaying: image: /home/datahearth/Pictures/assets/wallpapers/4.png
- DP-2: 1920x1080, scale: 2, currently displaying: image: /home/datahearth/Pictures/assets/wallpapers/4.png
Init commands:
```bash
exec-once=/nix/store/2pz6jpcymjlbzbyi98vmwz9ssqx459r1-swww-0.9.5/bin/swww-daemon
exec-once=/nix/store/2pz6jpcymjlbzbyi98vmwz9ssqx459r1-swww-0.9.5/bin/swww img ~/Pictures/assets/wallpapers/4.png
```

EDIT: I've also tried with a different image format, same result

**Comment by AimForNaN** [comment]
I have the same problem on Arch. I suspected it was due to the daemon taking a lot longer to start than the previous version. By prepending `sleep 1 &&` to `swww img` it works, though it takes longer to set a wallpaper.

It would be nice if `swww img` launched the daemon if none exists so we can just issue one `exec-once` statement.

**Comment by DataHearth** [comment]
Gonna try this tonight! If it works, then that'll do for now. But it seems off to me that updating just one minor version add such a speed issue on daemon load.

**Comment by LGFae** [comment]
> But it seems off to me that updating just one minor version add such a speed issue on daemon load.
From `0.8.2` to `0.9.5` is actually quite a jump. A lot of things changed under the hood.

I would also like ask for you to test this on the latest git version to see if the issue still exists there.

**Comment by DataHearth** [comment]
@LGFae Thank you for tip! I've tried using the latest [commit](https://github.com/LGFae/swww/commit/90e205ea17ed0c103cfbd0472499d361e8aa0603) and it is working. I'll check what has been done between 0.9.5 and `HEAD` ^^.
@AimForNaN If you're using flakes, you can use directly the root flake provided ^^ => https://github.com/LGFae/swww?tab=readme-ov-file#nix
