### ISSUE TITLE
[Error] Failed to use swww with Ubuntu24.04 swww: failed to write serialized request

### ISSUE THREAD

**Issue by li-chx** [LGFae/swww#337]
Error: "failed to write serialized request: Broken pipe (os error 32)"
After Building and launching swww-daemon. The swww responsed an error info.
![图片](https://github.com/LGFae/swww/assets/60217414/042310bb-f988-4470-881f-f27e9890a1a7)
Today is my first day to try to use Hyprland. I can't sure if this issue is swww's issue.
However, tell me if you need further info.

**Comment by amberjennings** [comment]
Same issue on Arch+Sway with `swww-git`, though it seems to work fine with stable `swww`.

**Comment by shinobiultra** [comment]
Same issue here as well. Lmk if I can help by providing anything relevant.

**Comment by I-like-stuff** [comment]
I have this issue as well, using swww's flake so it's updated to the latest git automatically

**Comment by CarloCattano** [comment]
same here

**Comment by LGFae** [comment]
Definitely  a problem with either #331 or #333. We are currently going through a very large refactor, so some things may break like this. Expect things to be a little unstable for a while; apologies for the inconvenience,

**Comment by rkuklik** [comment]
Hello, I will try to look into this as soon as I can, but currently am on vacation, so apologies in advance.

Given that #335 is quite large and no way near its end, I will try to create a quick fix.

Sorry for the inconvenience.

**Comment by li-chx** [comment]
Enjoy your vacation! I don't want this bug ruined your good moment.
Looking forward for your fix.

**Comment by rkuklik** [comment]
Well since it was me who introduced it... I forgot realize that flakes and some other package managers track updates to main. Could @LGFae please branch off main and revert #333 for now? I don't want for swww to be randomly broken on update.

**Comment by LGFae** [comment]
Done. The `main` branch should be working now. **Note that release builds are still exploding on a `debug_assert` (which makes it rather embarrassing that we somehow missed this :sweat:) **, but release builds are working. Closing this.
