### ISSUE TITLE
swww restore dosen't remember resize method

### ISSUE THREAD

**Issue by JackKm** [LGFae/swww#343]
when setting wallpaper wit `resize fit` and later (after restart or killing daemon)
when using swww restore (or starting swww-daemon) wallpaper is restored with `resize crop` option.

expected behavior: 
wallpaper restored in the same resize mode as it was set.

swww: 0.9.5 and master
system: nixos, hyprland

**Comment by LGFae** [comment]
Duplicate of #336.
