### ISSUE TITLE
Background does not update until next call to swww (just swww clear)

### ISSUE THREAD

**Issue by Squamto** [LGFae/swww#346]
I am using swww on NixOS with Hyprland. I am on version 0.9.5 (nixos-unstable)
When I do `swww clear 0a0a0a` nothing happens, until the next call to swww. Even if it is just `swww query`. `swww init` and `swww-daemon` will also trigger the background update, whilst printing an error.
Using `swww img` does change the background immediately to the specified image.

**Comment by LGFae** [comment]
I believe this is already fixed in the git version.
