### ISSUE TITLE
Package swww for fedora

### ISSUE THREAD

**Issue by glesaout** [LGFae/swww#347]
Hello, 
I know that it is possible to get it working using COPR or by compiling it myself but it could be great to consider packaging it officially. 

Now that Fedora supports bleeding edge things like Hyprland, having swww alongside could be nice.
If I can help in any way with this, how could I ?

**Comment by LGFae** [comment]
I do not know. You'd have to look up and figure it out yourself. I can answer questions about the build process, but even that should be pretty straightforward. I do not actually do any packaging; other people do it for their desired distro.

**Comment by ttimasdf** [comment]
I found a COPR here at https://copr.fedorainfracloud.org/coprs/materka/swww/ . I'm not the author, so use at your own risk..

```bash
sudo dnf copr enable materka/swww
sudo dnf install swww
```

source repo: https://github.com/materka/swww

build spec: https://github.com/materka/rpm-packages/blob/main/swww/swww.spec
