### ISSUE TITLE
Some gifs take a very long time to play

### ISSUE THREAD

**Issue by Eugenenoble2005** [LGFae/swww#354]
I'm using ffmpeg to convert 4k 60fps videos to 720p 10fps gifs like so:
```
ffmpeg -i mylivewallpapers-com-Zero-Two-Night-Rays-4K.mp4 -vf "fps=10,scale=-1:720p" -loop 0 nightray.gif
```
I can use them with swww but the inital startup time is over 30seconds long even on restart. Some other low quality gifs play almost instantly. Is there a more efficient way to convert them for swww or perhaps is my computer too slow to play to allow swww efficently play them?

**Comment by Eugenenoble2005** [comment]
For anyone having this problem, you can compromise reasonable on duration,resolution and framerate depending on your mp4 to get smaller gifs and better results with swww.
```
//crop the first 2 seconds at 1080p 10fps
ffmpeg -ss 0 -t 2 -i mylivewallpapers-com-Zero-Two-Night-Rays-4K.mp4 -vf "fps=10,scale=-1:1080p" -loop 0 nightray.gif
```

**Comment by LGFae** [comment]
This is a bug with the cache. After the first startup, subsequent loads should be instant. Can you try it out in the latest git version? I do believe this is already fixed.

**Comment by Eugenenoble2005** [comment]
Just upgraded to the -git version @LGFae . Works perfect now and starts instantly after initial cache time even on larger higher quality gifs. Also looks like a memory leak of some sort was repaired as mem usage is down almost a 100% from the standard release. Thank you for this wonderful tool.
