### ISSUE TITLE
GIFs are not being cached and are always loaded again and agian at start up 

### ISSUE THREAD

**Issue by AnkurAlpha** [LGFae/swww#357]
As the title says, swww is not able to cache the GIFs in my system , AFAIK when I first started using it , the activity was like this : 
~~~
1. when loading the GIF first time it use to take some 2 -3 minutes ( maybe, because it is loading the GIF and caching it )
2. next time when I tried to load it , it used to get loaded in 2 -3 seconds 
3. the speed of loading was 2 -3 seconds until I used cleanup the cache by `swww clean-cache` command 
~~~
Now what is happening is that it always takes time of around 2 -3 minutes to load even though it was previously loaded last time when I was working on my system .

**Comment by LGFae** [comment]
I believe this is already fixed in the git version.

**Comment by AnkurAlpha** [comment]
No, I just installed swww-git version , but that also has the same issue

**Comment by AnkurAlpha** [comment]
A re-build after git clone solved the issue .
