### ISSUE TITLE
panic while starting the swww-daemon 

### ISSUE THREAD

**Issue by wangluyi1982** [LGFae/swww#384]
thread 'main' panicked at daemon/src/wayland/globals.rs:155:9:
Compositor does not implement required interface: zwlr_layer_shell_v1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by kerty0** [comment]
The Wayland composer you are using doesn't support the protocol required for swww to work.

**Comment by LGFae** [comment]
@kerty0 is correct; `zwlr_layer_shell_v1` protocol must be supported by your compositor for `swww` to work. `gnome`, for example, does not implement it, and so `swww`  does not work with `gnome`.
