### ISSUE TITLE
Removing `/proc` traversal code

### ISSUE THREAD

**Issue by thedmm** [LGFae/swww#78]
I'm talking about `is_daemon_running()` in `src/main.rs`.  I understand why the daemon check was necessary (I read through #11 and #26), but I think there's a much cleaner solution to this problem: daemons can use `inotify` to check whether the socket they created has been removed or not.  If a running daemon determines that its socket was removed, it should exit immediately.  When a new daemon is started, it immediately removes any existing socket file, which will force past daemons (if they exist) to exit.  There's a nice Rust crate for using `inotify` (which is also, quite helpfully, called `inotify`), and since `inotify` instances are just file descriptors, they can be inserted into the daemon's main event loop quite easily.

I think this is a better solution because 1) it doesn't require traversing the entirety of `/proc` whenever the daemon starts up; 2) it allows `swww init` to deal with possibly-existing daemons better; and 3) it allows the daemon process to detect that its socket file has been removed and to exit accordingly, which it currently does not do.  I'm not asking you to implement this feature - I'd quite like to, actually - but I want to confirm that if I do implement it and open an MR for it, it would be accepted.

**Comment by thedmm** [comment]
This feature would also eliminate `Request::Kill`, and the loop used to check that the daemon dies (`src/main.rs:66-81`), making the code far simpler (`swww kill` would simply remove the socket file; the daemon would kill itself automatically).

**Comment by Horus645** [comment]
The problem I have with this is that I believe `swww init` should just exit with an error if there's already a daemon running. That is, I don't want it to make the already exisiting daemons exit. This would make the background turn back into black, interrupting any animations as well...

**Comment by thedmm** [comment]
I agree, that's not a good thing.  However, it is also expected that `swww init` is only called when the system is starting up.  If it is called again at any other time, it is almost certainly a user-driven action, and they would be aware that they are reloading the daemon.  I doubt there would be a case where the daemon dies without the user expecting it.

If this is still an issue, the solution for #65 would help as well (perhaps done per-output?).  I think that animations are relatively rare and short, so interrupting them would be uncommon; but the rest of the time, the daemon would correctly reload and display the last image.  The user would clearly be able to tell that the daemon reloaded (because of the background would go blank in between the two daemon instances), but once again, this would be expected if they restarted `swww`.

**Comment by flick0** [comment]
ive seen ppl use `sww init` (including me) in a script where u arent sure swww is currently running or not, in that case its useful that it just exits with an error instead of turning ur wallpaper black

**Comment by LGFae** [comment]
I think we have a good solution for this now. We can just try pinging the daemon. If it returns, then it is already running.
