### ISSUE TITLE
Fractional scale support

### ISSUE THREAD

**Issue by WhyNotHugo** [LGFae/swww#91]
The protocol for native fractional scale has been merged upstream as [wp-fractional-scale-v1](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143).

It is also [available in wayland-rs](https://docs.rs/wayland-protocols/0.30.0/wayland_protocols/wp/fractional_scale/v1/client/index.html).

Implementing this could result in sharper images when using fractional scale, and less overhead (since the compositor won't need to resize as much).

**Comment by WhyNotHugo** [comment]
Might be a good oportunity to implement [wl_surface.preferred_buffer_scale](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/220), where the compositor explicitly informs of the desired scale.

**Comment by Horus645** [comment]
Would this also help with #40?

**Comment by WhyNotHugo** [comment]
Probably. I'm pretty sure fractional scaling is messing up those values.

**Comment by Diaoul** [comment]
Is this lack of support the reason why the grow animation is laggy on a scaled monitor? :thinking:

**Comment by Horus645** [comment]
> Is this lack of support the reason why the grow animation is laggy on a scaled monitor? :thinking: 

I think that's unlikely. You could test it by setting the scale factor to a whole number and seeing if it still lags.

**Comment by Diaoul** [comment]
I don't have any visible lag when using non-scaled 4k monitor.

However I stumbled upon #108 and manage to workaround that. Doing so, I've found something weird in the logs: the same monitor (the scaled one) shows up twice:

Here is with scaling factor of 1:
```
❯ swww init --no-daemon
08:36:03 [INFO] (main) Initialization succeeded! Starting main loop...
08:36:03 [INFO] (main) failed to find cached image for monitor 'eDP-1'
08:36:03 [INFO] (main) failed to find cached image for monitor 'DP-4'
08:36:03 [INFO] (main) failed to find cached image for monitor 'DP-7'
```

That's with scaling factor of 1.5:
```
❯ swww init --no-daemon
08:37:50 [INFO] (main) Initialization succeeded! Starting main loop...
08:37:50 [INFO] (main) failed to find cached image for monitor 'eDP-1'
08:37:50 [INFO] (main) failed to find cached image for monitor 'DP-4'
08:37:50 [INFO] (main) failed to find cached image for monitor 'DP-7'
08:37:50 [INFO] (main) failed to find cached image for monitor 'DP-7'
```

Probably the reason why the animation seems laggy: there are actually 2 overlapping ones :thinking: 

Both `hyprctl` and `wlr-randr` report 3 monitors, not sure where the confusion from `swww` comes from.

**Comment by Horus645** [comment]
@Diaoul, sorry for not responding for so long.

The latest master has changed a lot (including a full rewrite of the wayland code), so I'd have to ask you to retest those findings. If the issues remain, you should open a new issue so we can track them better.

**Comment by Diaoul** [comment]
No worries, I'll test again in the coming days and report back!

**Comment by BANanaD3V** [comment]
Anything new? for me gif wallpaper and transitions are laggy with scaling but perfect without. Nixos, hyprland

**Comment by Diaoul** [comment]
Tried again, indeed very laggy.

**Comment by WhyNotHugo** [comment]
For shotman, I used an `Enum` to save the current scale:

https://git.sr.ht/~whynothugo/shotman/tree/09a5219028a0f37e86fc592efa43865a684e9ddd/item/src/main.rs#L255-265

Each of these values comes from a different source (which may or may not be available depending on the compositor's protocol support). When the compositor informs of a new scale, I only save it if it is a variant that is defined below the current one. It's somewhat messy, but cover all scenarios.

I wish I knew how to make proper reusable code; most of the logic is too intertwined with the rest of shotman.

**Comment by LGFae** [comment]
This is probably next on the list. Took a while, but we'll get there :sweat:

**Comment by LGFae** [comment]
@WhyNotHugo your code was actually very helpful. It would have taken me a lot longer without using it as a basic reference. Thanks!
